services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: colegio
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  estudiante:
    build: ./estudiante
    depends_on:
      mysql:
        condition: service_started
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=colegio

  evaluacion:
    build: ./evaluacion
    depends_on:
      mysql:
        condition: service_started
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=colegio
